
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: hrbac
      POSTGRES_PASSWORD: hrbac
      POSTGRES_DB: hrbac
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
